name: C/C++ CI

on:
  push:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true  # This ensures submodules are cloned

    # Install system dependencies
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake g++ make pkg-config \
                            libsdl2-dev libopengl-dev \
                            libgtest-dev

    # Build and install Google Test manually
    - name: Install Google Test
      run: |
        cd /usr/src/gtest
        sudo cmake .
        sudo make
        sudo cp lib/*.a /usr/lib

    # Create build directory and configure project
    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake ..

    # Build the project
    - name: Build the project
      run: |
        cd build
        make

    # Build the tests
    - name: Build the Tests
      run: |
        cd build
        make tests

    # Run the tests
    - name: Run Tests
      run: |
        cd build
        ctest
